package HelloApp;


/**
* HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Thursday, April 11, 2019 10:21:59 PM IST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
